[package]
name = "merkle-tree"
version = "0.1.0"
edition = "2021"

[dependencies]

sha2 = "0.10.0"

rand = "0.8.0"

hex = "0.4.3"

num-bigint = { version = "0.4", features = ["rand"] }

num-traits = "0.2.19"

lazy_static = "1.4"

curv-kzen = "0.10"

curve25519-dalek = "3.1.0"
